GET http://localhost:3004/todos HTTP/1.1

###

POST http://localhost:3004/todo/new HTTP/1.1
Content-Type: application/json

{
"text": "Pick up boat"
}

###

DELETE http://localhost:3004/todo/delete/63e7499f42b8cbfa38754e0d HTTP/1.1

###

GET http://localhost:3004/todo/complete/60e585d86177f95ff0574323

###

PUT http://localhost:3002/todo/update/60e585d86177f95ff0574323 Content-Type: application/json

{
"text": "Go Shopping for Milk"
}